In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("~/Desktop/Stage/Datacancer.csv")
data.head()

,measure_id,measure_name,location_id,location_name,sex_id,sex_name,age_id,age_name,cause_id,cause_name,metric_id,metric_name,year,val,upper,lower
0,2,AVAIs (Années de Vie Ajustées en fonction de l...,196,Afrique du Sud,3,Les deux,22,Tout age,298,VIH/SIDA,3,Taux,2000,21126.732715,22161.378011,20197.485851
1,2,AVAIs (Années de Vie Ajustées en fonction de l...,205,Côte d’Ivoire,3,Les deux,22,Tout age,480,Cancer de la thyroïde,3,Taux,2000,6.470223,9.624114,4.520661
2,2,AVAIs (Années de Vie Ajustées en fonction de l...,142,Iran,3,Les deux,22,Tout age,298,VIH/SIDA,3,Taux,2001,12.469178,14.404437,11.079337
3,2,AVAIs (Années de Vie Ajustées en fonction de l...,81,Allemagne,3,Les deux,22,Tout age,414,Cancer de l’estomac,3,Taux,2001,398.651368,425.679783,372.994342
4,2,AVAIs (Années de Vie Ajustées en fonction de l...,81,Allemagne,3,Les deux,22,Tout age,417,Cancer du foie,3,Taux,2001,117.004008,122.420699,110.293766

In [3]:
# 1️⃣ Sélectionner les colonnes qui t'intéressent
colonnes_utiles = ["year", "location_name", "cause_name", "val"]

data1 = data[colonnes_utiles].copy()

# 2️⃣ Renommer les colonnes
data1 = data1.rename(columns={
    "year": "Années",
    "location_name": "Pays",
    "cause_name": "Cause",
    "val": "Taux"
})
data1.head()

   Années            Pays                  Cause          Taux
0    2000  Afrique du Sud               VIH/SIDA  21126.732715
1    2000   Côte d’Ivoire  Cancer de la thyroïde      6.470223
2    2001            Iran               VIH/SIDA     12.469178
3    2001       Allemagne    Cancer de l’estomac    398.651368
4    2001       Allemagne         Cancer du foie    117.004008

In [4]:
data1.shape

(4004, 4)

#

In [5]:
# 1) Optionnel : s'assurer que les années sont bien des entiers
data1["Années"] = data1["Années"].astype(int)

# 2) Pivot : chaque cause devient une colonne
data2 = data1.pivot_table(
    index=["Années", "Pays"],   # lignes = combinaison année + pays
    columns="Cause",            # colonnes = les différentes causes
    values="Taux",              # valeurs dans les cellules
    aggfunc="first"             # ou "sum", "mean"... si doublons possibles
)

# 3) Remettre l'index à plat
data2 = data2.reset_index()

# 4) (Optionnel) enlever le nom de l'index des colonnes
data2.columns.name = None

# 5) (Optionnel) remplacer les NaN par 0 ou "X" si tu préfères
# df_wide = df_wide.fillna("X")

data2.head()

,Années,Pays,Cancer de la thyroïde,Cancer de l’estomac,Cancer de l’utérus,Cancer du foie,Cancer du sein,Cancer du testicule,VIH/SIDA
0,2000,Afrique du Sud,6.693356,131.697408,15.423897,131.770679,176.759697,5.076181,21126.732715
1,2000,Allemagne,27.942376,416.349628,59.467820,114.701698,642.003829,16.176612,47.915219
2,2000,Brésil,10.286505,272.928385,24.867953,30.561424,217.635615,7.718421,453.533734
3,2000,Canada,13.061176,212.297142,41.727489,81.654610,504.857250,8.444469,98.207731
4,2000,Chili,15.127299,540.309575,21.829441,38.431916,218.267157,40.513728,179.893799

In [6]:
data2 = data2.rename(columns={ "Cancer de la thyroïde": "Cancer_thyroïde", 
                        "Cancer de l’estomac": "Cancer_Estomac", 
                        "Cancer de l’utérus": "Cancer_Utérus",
                        "Cancer du foie": "Cancer_Foie",
                        "Cancer du sein": "Cancer_Sein",
                        "Cancer du testicule":"Cancer_Testicule",
                       })
data2.head()

,Années,Pays,Cancer_thyroïde,Cancer_Estomac,Cancer_Utérus,Cancer_Foie,Cancer_Sein,Cancer_Testicule,VIH/SIDA
0,2000,Afrique du Sud,6.693356,131.697408,15.423897,131.770679,176.759697,5.076181,21126.732715
1,2000,Allemagne,27.942376,416.349628,59.467820,114.701698,642.003829,16.176612,47.915219
2,2000,Brésil,10.286505,272.928385,24.867953,30.561424,217.635615,7.718421,453.533734
3,2000,Canada,13.061176,212.297142,41.727489,81.654610,504.857250,8.444469,98.207731
4,2000,Chili,15.127299,540.309575,21.829441,38.431916,218.267157,40.513728,179.893799

In [7]:
data2 = data2.sort_values(["Pays", "Années"]).reset_index(drop=True)
data2.head()

,Années,Pays,Cancer_thyroïde,Cancer_Estomac,Cancer_Utérus,Cancer_Foie,Cancer_Sein,Cancer_Testicule,VIH/SIDA
0,2000,Afrique du Sud,6.693356,131.697408,15.423897,131.770679,176.759697,5.076181,21126.732715
1,2001,Afrique du Sud,6.608833,127.524049,15.438783,129.330777,172.018849,4.962910,24856.531168
2,2002,Afrique du Sud,6.539335,124.374873,15.400269,127.492964,170.407084,4.924796,28413.659156
3,2003,Afrique du Sud,6.551281,121.638201,15.357450,124.881330,170.711113,4.941108,31314.350156
4,2004,Afrique du Sud,6.393602,115.205262,15.116203,119.238627,170.457759,4.780689,33291.515421

In [8]:
data2.isnull().sum()

Années              0
Pays                0
Cancer_thyroïde     0
Cancer_Estomac      0
Cancer_Utérus       0
Cancer_Foie         0
Cancer_Sein         0
Cancer_Testicule    0
VIH/SIDA            0
dtype: int64

In [9]:
data2.to_csv("DataCancerfinal.csv",index=False, sep=';')